version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
    labels:
      - "dependencies"
    groups:
      production:
        dependency-type: "production"
      dev:
        dependency-type: "development"
